version: '3.6'

services: 
  virt-manager:
    image: crazyp/virt-manager:debian
    restart: always
    ports:
      - 8185:80
    environment:
    # Substitute comma separated qemu connect strings, e.g.: 
    # HOSTS: "['qemu+ssh://user@host1/system', 'qemu+ssh://user@host2/system']"
      HOSTS: "[]"
    #volumes:
    # Substitute location of ssh private key, e.g.:
    # - /home/user/.ssh/id_rsa:/root/.ssh/id_rsa:ro
